base_config: ../../configs/mnist_common_relaxation_sabc.yaml
data: {protocol: class_split}
model: {activation: relu}
train: {relaxation_optimizer_policy: reset}
logging: {run_name: mnist_class_split_SABC_reset_relu_seed1337_normnone}
